# Generated by Django 4.2.1 on 2023-05-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='order_n',
            field=models.SmallIntegerField(default=1, verbose_name='Order'),
        ),
    ]
